<?php require __DIR__.'/../../../includes/header.php'; $base=project_base_url(); ?>
<div class="page-head"><div><p class="eyebrow">Administration</p><h1>Admin Dashboard</h1><p>Overview of your inventory system and daily activity.</p></div><div class="head-actions"><a class="btn light" href="<?=e($base)?>/admin/reports.php">▤ View Reports</a><a class="btn" href="<?=e($base)?>/admin/products.php">＋ Add Product</a></div></div>
<div class="cards">
<div class="stat-card"><div class="stat-top"><span class="stat-label">Total Users</span><span class="stat-icon">♙</span></div><div class="stat-value"><?=e($stats['users'])?></div><div class="stat-note">Registered system accounts</div></div>
<div class="stat-card"><div class="stat-top"><span class="stat-label">Products</span><span class="stat-icon">▣</span></div><div class="stat-value"><?=e($stats['products'])?></div><div class="stat-note"><?=e($stats['categories'])?> categories</div></div>
<div class="stat-card"><div class="stat-top"><span class="stat-label">Stock Units</span><span class="stat-icon">◈</span></div><div class="stat-value"><?=e($stats['stock'])?></div><div class="stat-note"><?=e($stats['low'])?> need attention</div></div>
<div class="stat-card"><div class="stat-top"><span class="stat-label">Sales Value</span><span class="stat-icon">৳</span></div><div class="stat-value">৳<?=number_format($stats['sales'],2)?></div><div class="stat-note">Recorded sales total</div></div>
</div>
<div class="grid2"><section class="panel"><div class="panel-head"><div><h2>Low Stock Alert</h2><span class="panel-sub">Products at or below reorder level</span></div><a class="btn small light" href="<?=e($base)?>/admin/reports.php">Full report</a></div><div class="table-wrap"><table class="table"><tr><th>Product</th><th>SKU</th><th>Category</th><th>Available</th><th>Reorder</th></tr><?php foreach($low as $p):?><tr><td><b><?=e($p['name'])?></b></td><td><?=e($p['sku'])?></td><td><?=e($p['category']??'Uncategorized')?></td><td><span class="badge red"><?=e($p['quantity'])?> units</span></td><td><?=e($p['reorder_level'])?></td></tr><?php endforeach;?><?php if(!$low):?><tr><td colspan="5" class="empty">Great! No low-stock products right now.</td></tr><?php endif;?></table></div></section>
<section class="panel"><div class="panel-head"><div><h2>Quick Actions</h2><span class="panel-sub">Manage the system faster</span></div></div><div class="quick-grid"><a class="quick-link" href="<?=e($base)?>/admin/users.php"><span>♙</span><div><b>Manage Users</b><small>Add, edit or deactivate</small></div></a><a class="quick-link" href="<?=e($base)?>/admin/products.php"><span>▣</span><div><b>Manage Products</b><small>Add, edit or remove</small></div></a><a class="quick-link" href="<?=e($base)?>/admin/categories.php"><span>◇</span><div><b>Categories</b><small>Organize products</small></div></a><a class="quick-link" href="<?=e($base)?>/profile/index.php"><span>◉</span><div><b>My Profile</b><small>Edit only your account</small></div></a></div></section></div>
<br><section class="panel"><div class="panel-head"><div><h2>Recent Activity</h2><span class="panel-sub">Latest sales and purchase records</span></div></div><div class="table-wrap"><table class="table"><tr><th>Type</th><th>Item</th><th>Amount</th><th>By</th><th>Date</th></tr><?php foreach($recent as $r):?><tr><td><span class="badge <?=$r['activity']==='Sale'?'green':'gray'?>"><?=e($r['activity'])?></span></td><td><?=e($r['item'])?></td><td>৳<?=number_format((float)$r['amount'],2)?></td><td><?=e($r['user_name'])?></td><td><?=e(date('d M Y, h:i A',strtotime($r['created_at'])))?></td></tr><?php endforeach;?><?php if(!$recent):?><tr><td colspan="5" class="empty">No recent activity yet.</td></tr><?php endif;?></table></div></section>
<?php require __DIR__.'/../../../includes/footer.php'; ?>
