<?php require __DIR__.'/../../../includes/header.php'; ?>
<div class="page-head"><div><p class="eyebrow">Administration</p><h1>Overall Reports</h1><p>Complete sales, purchase, profit/loss and current stock overview.</p></div></div>
<div class="cards cards-2">
<div class="stat-card"><div class="stat-label">Sales Revenue</div><div class="stat-value">৳<?=number_format((float)$summary['sales']['total'],2)?></div><div class="stat-note"><?=e($summary['sales']['n'])?> completed sales</div></div>
<div class="stat-card"><div class="stat-label">Purchase Cost</div><div class="stat-value">৳<?=number_format((float)$summary['purchases']['total'],2)?></div><div class="stat-note"><?=e($summary['purchases']['n'])?> completed purchases</div></div>
<div class="stat-card"><div class="stat-label">Sales Profit / Loss</div><div class="stat-value">৳<?=number_format(abs((float)$summary['net_sales_margin']),2)?></div><div class="stat-note"><?=($summary['net_sales_margin']>=0?'Overall sales profit':'Overall sales loss')?></div></div>
<div class="stat-card"><div class="stat-label">Purchase Price Impact</div><div class="stat-value">৳<?=number_format(abs((float)$summary['net_purchase_margin']),2)?></div><div class="stat-note"><?=($summary['net_purchase_margin']>=0?'Purchases have profit potential':'Purchases have loss risk')?></div></div>
</div>
<br><section class="panel"><div class="panel-head"><div><h2>Profit & Loss Summary</h2><span class="panel-sub">Sales: selling price compared with purchase cost. Purchases: selling price compared with buying price.</span></div></div>
<div class="table-wrap"><table class="table"><tr><th>Area</th><th>Profit</th><th>Loss</th><th>Net Result</th></tr>
<tr><td><b>Sales</b></td><td>৳<?=number_format(max(0,(float)$summary['net_sales_margin']),2)?></td><td>৳<?=number_format(max(0,-(float)$summary['net_sales_margin']),2)?></td><td><span class="badge <?=$summary['net_sales_margin']>=0?'green':'red'?>"><?=$summary['net_sales_margin']>=0?'Profit':'Loss'?>: ৳<?=number_format(abs((float)$summary['net_sales_margin']),2)?></span></td></tr>
<tr><td><b>Purchases</b></td><td>৳<?=number_format(max(0,(float)$summary['net_purchase_margin']),2)?></td><td>৳<?=number_format(max(0,-(float)$summary['net_purchase_margin']),2)?></td><td><span class="badge <?=$summary['net_purchase_margin']>=0?'green':'red'?>"><?=$summary['net_purchase_margin']>=0?'Potential Profit':'Loss Risk'?>: ৳<?=number_format(abs((float)$summary['net_purchase_margin']),2)?></span></td></tr>
</table></div></section>
<br><section class="panel"><div class="panel-head"><div><h2>Current Stock Report</h2><span class="panel-sub">Current quantity, selling price and latest cost price</span></div></div><div class="table-wrap"><table class="table"><tr><th>SKU</th><th>Product</th><th>Quantity</th><th>Cost Price</th><th>Selling Price</th><th>Status</th></tr><?php foreach($summary['stock'] as $p):?><tr><td><?=e($p['sku'])?></td><td><?=e($p['name'])?></td><td><?=e($p['quantity'])?></td><td>৳<?=number_format((float)$p['cost_price'],2)?></td><td>৳<?=number_format((float)$p['price'],2)?></td><td><?=$p['quantity']==0?'<span class="badge red">Out of stock</span>':($p['quantity']<=$p['reorder_level']?'<span class="badge red">Low stock</span>':'<span class="badge green">Healthy</span>')?></td></tr><?php endforeach;?></table></div></section>
<?php require __DIR__.'/../../../includes/footer.php'; ?>