<?php
require_once __DIR__.'/auth.php';
$u=current_user();$flash=get_flash();$role=$u['role']??'';$base=project_base_url();$path=str_replace('\\','/',$_SERVER['SCRIPT_NAME']??'');$current=basename($path);
$isInventory=$role==='Inventory Manager';$isPurchase=$role==='Purchase Officer';$isStaff=$role==='Sales Staff';
$themeClass=($isInventory||$isPurchase||$isStaff)?'role-blue':''; $isProfilePath=str_contains($path,'/profile/');
$dashboard=$isInventory?$base.'/inventory_manager/index.php':($isPurchase?$base.'/purchase_officer/index.php':$base.'/staff/index.php');
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title??'StockFlow')?></title><link rel="stylesheet" href="<?=e($base)?>/assets/css/style.css"></head><body class="<?=$themeClass?>"><div class="app-shell"><header class="topbar"><div class="top-left"><button class="mobile-toggle" type="button" aria-label="Open menu" onclick="document.body.classList.toggle('sidebar-open')">☰</button><a class="brand" href="<?=e($dashboard)?>"><span class="brand-mark">S</span><span>Stock<span class="brand-accent">Flow</span></span></a></div><div class="top-actions"><div class="user-chip"><span class="avatar"><?=e(strtoupper(substr($u['name']??'U',0,1)))?></span><span class="user-meta"><b><?=e($u['name']??'User')?></b><small><?=e($role)?></small></span></div><a class="icon-link" href="<?=$base?>/profile/index.php" title="My Profile">⚙</a><a class="logout-link" href="<?=$base?>/logout.php">Logout</a></div></header><div class="layout"><aside class="sidebar" id="sidebar"><div class="sidebar-label">MAIN MENU</div><a class="nav-link <?=$current==='index.php'&&!$isProfilePath?'active':''?>" href="<?=$dashboard?>"><span>⌂</span> Dashboard</a>
<?php if($isInventory): ?><div class="sidebar-label">INVENTORY</div><a class="nav-link <?=$current==='stock_in.php'?'active':''?>" href="<?=$base?>/inventory_manager/stock_in.php"><span>＋</span> Stock In</a><a class="nav-link <?=$current==='stock_out.php'?'active':''?>" href="<?=$base?>/inventory_manager/stock_out.php"><span>−</span> Stock Out</a><a class="nav-link <?=$current==='adjustment.php'?'active':''?>" href="<?=$base?>/inventory_manager/adjustment.php"><span>↔</span> Stock Adjustment</a><a class="nav-link <?=$current==='reports.php'?'active':''?>" href="<?=$base?>/inventory_manager/reports.php"><span>▥</span> Reports</a><?php endif; ?>
<?php if($isPurchase): ?><div class="sidebar-label">PURCHASE</div><a class="nav-link <?=$current==='suppliers.php'?'active':''?>" href="<?=$base?>/purchase_officer/suppliers.php"><span>♧</span> Suppliers</a><a class="nav-link <?=$current==='purchases.php'?'active':''?>" href="<?=$base?>/purchase_officer/purchases.php"><span>＋</span> Purchases</a><a class="nav-link <?=$current==='returns.php'?'active':''?>" href="<?=$base?>/purchase_officer/returns.php"><span>↩</span> Purchase Returns</a><a class="nav-link <?=$current==='reports.php'?'active':''?>" href="<?=$base?>/purchase_officer/reports.php"><span>▥</span> Reports</a><?php endif; ?>
<?php if($isStaff): ?><div class="sidebar-label">SALES</div><a class="nav-link <?=$current==='customers.php'?'active':''?>" href="<?=$base?>/staff/customers.php"><span>♙</span> Customers</a><a class="nav-link <?=$current==='sales.php'?'active':''?>" href="<?=$base?>/staff/sales.php"><span>৳</span> Sales</a><a class="nav-link <?=$current==='returns.php'?'active':''?>" href="<?=$base?>/staff/returns.php"><span>↩</span> Sales Returns</a><a class="nav-link <?=$current==='reports.php'?'active':''?>" href="<?=$base?>/staff/reports.php"><span>▥</span> Reports</a><?php endif; ?>
<div class="sidebar-label">ACCOUNT</div><a class="nav-link <?=$path!==''&&str_contains($path,'/profile/')?'active':''?>" href="<?=$base?>/profile/index.php"><span>◉</span> My Profile</a><div class="sidebar-bottom"><div class="secure-box"><span>✓</span><div><b>Secure Session</b><small>Role-based access + CSRF.</small></div></div></div></aside><main class="main-content"><?php if($flash): ?><div class="flash <?=e($flash['type'])?>"><?=e($flash['message'])?></div><?php endif; ?>
